spring.datasource.url=jdbc:mysql://localhost:5050/traffic_fine_db
spring.datasource.username=roo
spring.datasource.password=YOUR_DB_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

payhere.merchant-id=YOUR_PAYHERE_MERCHANT_ID
payhere.merchant-secret=YOUR_PAYHERE_MERCHANT_SECRET
payhere.currency=LKR
payhere.notify-url=https://YOUR_PUBLIC_URL/api/payments/notify
payhere.return-url=http://localhost:5173/payment-success
payhere.cancel-url=http://localhost:5173/payment-cancel
payhere.checkout-url=https://sandbox.payhere.lk/pay/checkout

sms.provider=notifylk
sms.notifylk.user-id=YOUR_NOTIFYLK_USER_ID
sms.notifylk.api-key=YOUR_NOTIFYLK_API_KEY
sms.notifylk.sender-id=YOUR_NOTIFYLK_SENDER_ID