spring.application.name=traffic-fine-backend

spring.datasource.url=jdbc:mysql://localhost:3306/traffic_fine_db
spring.datasource.username=root
spring.datasource.password=Mysql@200139

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


payhere.merchant-id=1236290
payhere.merchant-secret=MzM3OTMxNDk2MDEyNDQyMzg0ODAxMjcwODM5MjM5MTY1MDA5MTk0
payhere.currency=LKR
payhere.checkout-url=https://sandbox.payhere.lk/pay/checkout
payhere.return-url=http://localhost:5173/payment-success
payhere.cancel-url=http://localhost:5173/payment-cancel
payhere.notify-url=https://YOUR_PUBLIC_URL/api/payments/notify